# Generated by rust codes
execute positioned ^0.00000 ^ ^0.00000 run function battleapi:line_cb
execute positioned ^0.00000 ^ ^0.50000 run function battleapi:line_cb
execute positioned ^0.00000 ^ ^1.00000 run function battleapi:line_cb
execute positioned ^0.50000 ^ ^0.00000 run function battleapi:line_cb
execute positioned ^-0.50000 ^ ^0.00000 run function battleapi:line_cb
execute positioned ^0.50000 ^ ^0.50000 run function battleapi:line_cb
execute positioned ^-0.50000 ^ ^0.50000 run function battleapi:line_cb
execute positioned ^0.50000 ^ ^1.00000 run function battleapi:line_cb
execute positioned ^-0.50000 ^ ^1.00000 run function battleapi:line_cb
execute positioned ^1.00000 ^ ^0.00000 run function battleapi:line_cb
execute positioned ^-1.00000 ^ ^0.00000 run function battleapi:line_cb
execute positioned ^1.00000 ^ ^0.50000 run function battleapi:line_cb
execute positioned ^-1.00000 ^ ^0.50000 run function battleapi:line_cb
execute positioned ^1.00000 ^ ^1.00000 run function battleapi:line_cb
execute positioned ^-1.00000 ^ ^1.00000 run function battleapi:line_cb
